[ -n "$PS1" ] && source ~/.bash_profile;

#THIS MUST BE AT THE END OF THE FILE FOR SDKMAN TO WORK!!!
export SDKMAN_DIR="/Users/abrown/.sdkman"
[[ -s "/Users/abrown/.sdkman/bin/sdkman-init.sh" ]] && source "/Users/abrown/.sdkman/bin/sdkman-init.sh"
