tap "dteoh/sqa"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-drivers"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/services"
cask "adoptopenjdk8"
brew "openssl"
brew "python"
brew "asciinema"
brew "augeas"
brew "awscli"
brew "azure-cli"
brew "bash"
brew "bash-completion@2"
brew "bfg"
brew "cmake"
brew "coreutils"
brew "dark-mode"
brew "dpkg"
brew "ffmpeg"
brew "findutils"
brew "gdub"
brew "git"
brew "git-lfs"
brew "git-sizer"
brew "gnu-sed"
brew "gnupg", link: false
brew "go"
brew "graphviz"
brew "grep"
brew "httpie"
brew "hub"
brew "jq"
brew "libdvdcss"
brew "libxml2"
brew "lolcat"
brew "mas"
brew "mercurial"
brew "moreutils"
brew "mosh"
brew "nmap"
brew "p7zip"
brew "pandoc"
brew "socat"
brew "ssh-copy-id"
brew "tmux"
brew "tree"
brew "unrar"
brew "vim"
brew "watch"
brew "wget"
brew "wimlib"
brew "zsh"
cask "1password"
cask "atom"
cask "avidemux"
cask "balenaetcher"
cask "boxer"
cask "docker"
cask "dropbox"
cask "encryptme"
cask "epic-games"
cask "firefox"
cask "gog-galaxy"
cask "google-backup-and-sync"
cask "gpg-suite"
cask "handbrake"
cask "intellij-idea"
cask "iterm2"
cask "kid3"
cask "lg-onscreen-control"
cask "logitech-myharmony"
cask "marked"
cask "microsoft-azure-storage-explorer"
cask "microsoft-teams"
cask "nightowl"
cask "openemu"
cask "pycharm-ce"
cask "selfcontrol"
cask "slack"
cask "sourcetree"
cask "steam"
cask "subler"
cask "sublime-text"
cask "synology-drive"
cask "vagrant"
cask "viscosity"
cask "visualvm"
cask "vlc"
cask "xld"
cask "zoomus"
cask "zulu11"
cask "zulu7"
cask "dteoh/sqa/slowquitapps"
mas "Airmail", id: 918858936
mas "Amphetamine", id: 937984704
mas "Apple Configurator 2", id: 1037126344
mas "Bridge Constructor Portal", id: 1316061122
mas "GarageBand", id: 682658836
mas "iMovie", id: 408981434
mas "iPhoto", id: 408981381
mas "Keynote", id: 409183694
mas "Magnet", id: 441258766
mas "NetSpot", id: 514951692
mas "Notability", id: 736189492
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Reeder", id: 880001334
mas "Server", id: 883878097
mas "Wunderlist", id: 410628904
# mas "Xcode", id: 497799835
