actions:
  add_authorized_keys: cat ~/.ssh/authorized_keys* | uniq > ~/.ssh/authorized_keys
  install_package_control: "{{@@ _dotdrop_dotpath @@}}/../script/install-package-control.sh ~/\"{{@@ sublime_home @@}}\""
config:
  backup: true
  create: true
  link_dotfile_default: link
  link_on_import: link
  dotpath: dotfiles
  upignore:
    - .DS_Store
    - .localized
  cmpignore:
    - .DS_Store
    - .localized
dotfiles:
  d_bin:
    src: bin
    dst: ~/bin
  d_desktop:
    src: Desktop
    dst: ~/Desktop
    chmod: 700
    link: link_children
    upignore:
      - Relocated Items
    cmpignore:
      - Relocated Items
  d_gradle_init_d:
    src: gradle_init.d
    dst: ~/.gradle/init.d
    link: link_children
  d_oh-my-zsh-custom:
    src: oh-my-zsh-custom
    dst: ~/.oh-my-zsh-custom
    link: link_children
  d_ssh:
    src: ssh
    dst: ~/.ssh
    link: link_children
    upignore:
      - authorized_keys
      - caas-abrown*
      - id_ed25519*
      - id_rsa*
      - sockets
      - synology*
    cmpignore:
      - authorized_keys
      - caas-abrown*
      - id_ed25519*
      - id_rsa*
      - sockets
      - synology*
    actions:
      - add_authorized_keys
  d_user:
    src: Library/Application Support/Sublime Text 3/Packages/User
    dst: "~/{{@@ sublime_home @@}}/Packages/User"
    link: link_children
    actions:
      - install_package_control
    upignore:
      - oscrypto-ca-bundle.crt
      - Package Control.cache
      - Package Control.last-run
      - Package Control.merged-ca-bundle
      - Package Control.user-ca-bundle
    cmpignore:
      - oscrypto-ca-bundle.crt
      - Package Control.cache
      - Package Control.last-run
      - Package Control.merged-ca-bundle
      - Package Control.user-ca-bundle
  f_aliases:
    src: aliases
    dst: ~/.aliases
  f_bashrc:
    src: bashrc
    dst: ~/.bashrc
  f_bash_profile:
    src: bash_profile
    dst: ~/.bash_profile
  f_bash_sessions_disable:
    src: bash_sessions_disable
    dst: ~/.bash_sessions_disable
  f_bash_profile-for-zsh:
    src: bash_profile-for-zsh
    dst: ~/.bash_profile
  f_bash_prompt:
    src: bash_prompt
    dst: ~/.bash_prompt
  f_curlrc:
    src: curlrc
    dst: ~/.curlrc
  f_exports:
    src: exports
    dst: ~/.exports
  f_finicky.js:
    src: finicky.js
    dst: ~/.finicky.js
  f_functions:
    src: functions
    dst: ~/.functions
  f_gitconfig:
    src: gitconfig
    dst: ~/.gitconfig
  f_gitconfig-confluent:
    src: gitconfig-confluent
    dst: ~/.gitconfig-confluent
  f_gitignore:
    src: gitignore
    dst: ~/.gitignore
  f_gradle_properties:
    src: gradle.properties
    dst: ~/.gradle/gradle.properties
    chmod: 600
  f_hgrc:
    src: hgrc
    dst: ~/.hgrc
  f_hushlogin:
    src: hushlogin
    dst: ~/.hushlogin
  f_m2_settings:
    src: m2_settings.xml
    dst: ~/.m2/settings.xml
    chmod: 600
  f_netrc:
    src: netrc
    dst: ~/.netrc
    chmod: 600
  f_path:
    src: path
    dst: ~/.path
  f_pip_conf:
    src: pip.conf
    dst: ~/.pip/pip.conf
  f_pypirc:
    src: pypirc
    dst: ~/.pypirc
    chmod: 600
  f_tmux.conf:
    src: tmux.conf
    dst: ~/.tmux.conf
  f_vimrc:
    src: vimrc
    dst: ~/.vimrc
  f_wgetrc:
    src: wgetrc
    dst: ~/.wgetrc
  f_zshenv:
    src: zshenv
    dst: ~/.zshenv
  f_zshrc:
    src: zshrc
    dst: ~/.zshrc
profiles:
  abrown-confluent:
    include:
      - abrown-confluent.notcharlie.com
  abrown-confluent.local:
    include:
      - abrown-confluent.notcharlie.com
  abrown-confluent.notcharlie.com:
    include:
      - default
      - mac
  exhubber:
    include:
      - exhubber.notcharlie.com
  exhubber.local:
    include:
      - exhubber.notcharlie.com
  exhubber.notcharlie.com:
    include:
      - default
      - mac
  mini-me:
    include:
      - mini-me.notcharlie.com
  mini-me.local:
    include:
      - mini-me.notcharlie.com
  mini-me.notcharlie.com:
    include:
      - default
      - mac
  pacman:
    include: pacman.notcharlie.com
  pacman.local:
    include: pacman.notcharlie.com
  pacman.notcharlie.com:
    include:
      - default
      - mac
  mac:
    variables:
      sublime_home: Library/Application Support/Sublime Text 3
    dotfiles:
      - d_desktop
      - d_user
      - f_finicky.js
  linux:
    variables:
      sublime_home: .config/sublime-text-3
    dotfiles:
      - d_user
  default:
    include:
      - zsh
  zsh:
    include:
      - shared
    dotfiles:
      - d_oh-my-zsh-custom
      - f_bash_profile-for-zsh
      - f_zshenv
      - f_zshrc
  bash:
    include:
      - shared
    dotfiles:
      - f_aliases
      - f_bash_profile
      - f_bash_prompt
      - f_bashrc
      - f_exports
      - f_functions
      - f_path
  shared:
    dotfiles:
      - d_bin
      - d_gradle_init_d
      - d_ssh
      - f_bash_sessions_disable
      - f_curlrc
      - f_gitconfig
      - f_gitconfig-confluent
      - f_gitignore
      - f_gradle_properties
      - f_hgrc
      - f_hushlogin
      - f_m2_settings
      - f_netrc
      - f_pip_conf
      - f_pypirc
      - f_tmux.conf
      - f_vimrc
      - f_wgetrc
