actions:
  add_authorized_keys: cat ~/.ssh/authorized_keys* | uniq > ~/.ssh/authorized_keys
  install_package_control: "{{@@ _dotdrop_dotpath @@}}/../script/lib/install-package-control ~/\"{{@@ sublime_home @@}}\""
  _pyenv_install: |
    if [ -d ~/.pyenv ]; then
      git -C ~/.pyenv pull --prune origin;
    else
      git clone https://github.com/pyenv/pyenv.git ~/.pyenv;
    fi
  _goenv_install: |
    if [ -d ~/.goenv ]; then
      git -C ~/.goenv pull --prune origin;
    else
      git clone https://github.com/syndbg/goenv.git ~/.goenv;
    fi
  _nvm_install: |
    if [ -d ~/.nvm ]; then
      git -C ~/.nvm pull --prune origin;
    else
      git clone https://github.com/nvm-sh/nvm.git ~/.nvm;
    fi
  _cc_dotfiles_install: |
    if [ -d ~/.cc-dotfiles ]; then
      git -C ~/.cc-dotfiles pull --prune origin;
    else
      git clone https://github.com/confluentinc/cc-dotfiles.git ~/.cc-dotfiles;
    fi
config:
  backup: true
  create: true
  force_chmod: true
  link_dotfile_default: link
  link_on_import: link
  dotpath: dotfiles
  upignore:
    - .DS_Store
    - .localized
  cmpignore:
    - .DS_Store
    - .localized
dotfiles:
  d_bin:
    src: bin
    dst: ~/bin
  d_config_coursier:
    src: config/coursier
    dst: ~/.config/coursier
    chmod: 700
    link: link_children
  d_config_gh:
    src: config/gh
    dst: ~/.config/gh
    chmod: 700
    link: link_children
  d_config_yapf:
    src: config/yapf
    dst: ~/.config/yapf
    link: link_children
  d_git_template:
    src: git-template
    dst: ~/.git-template
    link: nolink
  d_gradle_init_d:
    src: gradle_init.d
    dst: ~/.gradle/init.d
    link: link_children
  d_oh-my-zsh-custom:
    src: oh-my-zsh-custom
    dst: ~/.oh-my-zsh-custom
    link: link_children
    chmod: 700
  d_ssh:
    src: ssh
    dst: ~/.ssh
    link: link_children
    upignore:
      - authorized_keys
      - caas-abrown*
      - id_ed25519*
      - id_rsa*
      - sockets
      - synology*
    cmpignore:
      - authorized_keys
      - caas-abrown*
      - id_ed25519*
      - id_rsa*
      - sockets
      - synology*
    actions:
      - add_authorized_keys
  d_user:
    src: Library/Application Support/Sublime Text 3/Packages/User
    dst: "~/{{@@ sublime_home @@}}/Packages/User"
    link: link_children
    actions:
      - install_package_control
    upignore:
      - oscrypto-ca-bundle.crt
      - Package Control.cache
      - Package Control.last-run
      - Package Control.merged-ca-bundle
      - Package Control.user-ca-bundle
    cmpignore:
      - oscrypto-ca-bundle.crt
      - Package Control.cache
      - Package Control.last-run
      - Package Control.merged-ca-bundle
      - Package Control.user-ca-bundle
  f_aws_config:
    src: aws/config
    dst: ~/.aws/config
  f_bash_sessions_disable:
    src: bash_sessions_disable
    dst: ~/.bash_sessions_disable
  f_bash_profile-for-zsh:
    src: bash_profile-for-zsh
    dst: ~/.bash_profile
  f_config_hub:
    src: config/hub
    dst: ~/.config/hub
    chmod: 600
  f_curlrc:
    src: curlrc
    dst: ~/.curlrc
  f_finicky.js:
    src: finicky.js
    dst: ~/.finicky.js
  f_gitconfig:
    src: gitconfig
    dst: ~/.gitconfig
  f_gitconfig-confluent:
    src: gitconfig-confluent
    dst: ~/.gitconfig-confluent
  f_gitignore:
    src: gitignore
    dst: ~/.gitignore
  f_gradle_properties:
    src: gradle.properties
    dst: ~/.gradle/gradle.properties
    chmod: 600
  f_hgrc:
    src: hgrc
    dst: ~/.hgrc
  f_hushlogin:
    src: hushlogin
    dst: ~/.hushlogin
  f_m2_settings:
    src: m2_settings.xml
    dst: ~/.m2/settings.xml
    chmod: 600
    link: nolink
  f_netrc:
    src: netrc
    dst: ~/.netrc
    chmod: 600
  f_okta_aws_login_config:
    src: okta_aws_login_config
    dst: ~/.okta_aws_login_config
    chmod: 600
  f_pip_conf:
    src: pip.conf
    dst: ~/.pip/pip.conf
  f_pypirc:
    src: pypirc
    dst: ~/.pypirc
    chmod: 600
  f_tmux.conf:
    src: tmux.conf
    dst: ~/.tmux.conf
  f_vimrc:
    src: vimrc
    dst: ~/.vimrc
  f_wgetrc:
    src: wgetrc
    dst: ~/.wgetrc
  f_zshenv:
    src: zshenv
    dst: ~/.zshenv
  f_zshrc:
    src: zshrc
    dst: ~/.zshrc
  fake_cc_dotfiles:
    src:
    dst:
    actions:
      - _cc_dotfiles_install
  fake_pyenv:
    src:
    dst:
    actions:
      - _pyenv_install
  fake_goenv:
    src:
    dst:
    actions:
      - _goenv_install
  fake_nvm:
    src:
    dst:
    actions:
      - _nvm_install
profiles:
  abrown-confluent:
    include:
      - default
      - mac
      - confluent
  abrown-confluent.local:
    include:
      - abrown-confluent
  abrown-confluent.notcharlie.com:
    include:
      - abrown-confluent
  exhubber:
    include:
      - default
      - mac
      - personal
  exhubber.local:
    include:
      - exhubber
  exhubber.notcharlie.com:
    include:
      - exhubber
  mac:
    variables:
      sublime_home: Library/Application Support/Sublime Text 3
      mac: true
      ssh_agent: "{{@@ env['HOME'] @@}}/Library/Group Containers/2BUA8C4S2C.com.1password/t/agent.sock"
    dotfiles:
      - d_user
      - f_finicky.js
  linux_desktop:
    variables:
      sublime_home: .config/sublime-text-3
      ssh_agent: "{{@@ env['HOME'] @@}}/.1password/agent.sock"
    dotfiles:
      - d_user
  linux:
    variables:
      linux: true
  personal:
    variables:
      personal: true
  confluent:
    variables:
      confluent: true
    dotfiles:
      - d_config_coursier
      - d_config_yapf
      - f_aws_config
      - f_gitconfig-confluent
      - f_m2_settings
      - f_netrc
      - f_okta_aws_login_config
      - f_pip_conf
      - f_pypirc
      - fake_cc_dotfiles
      - fake_nvm
  default:
    variables:
      confluent: false
      linux: false
      mac: false
      personal: false
      ssh_agent: ''
    dynvariables:
      gh_cli_token: op item get "GitHub" --fields "gh cli token"
      github_netrc_token: op item get "GitHub" --fields "Confluent netrc"
      github_account: op item get "GitHub" --fields username
      hub_cli_token: op item get "GitHub" --fields "hub cli token"
      okta_default_device_token: op item get "Okta" --fields "gimme-aws-creds device_token"
      okta_username: op item get "Okta" --field username
      personal_email: op item get 2rou2jbvdvahrl4ov7wtxstdka --field email
      full_name: op item get 2rou2jbvdvahrl4ov7wtxstdka --fields "first name,last name" | tr ',' ' '
      work_email: echo "$({{@@ okta_username @@}})@confluent.io"
      personal_public_key: op item get "Default key" --field "public key"
      work_public_key: op item get Confluent --field "public key"
    include:
      - zsh
  zsh:
    include:
      - shared
    dotfiles:
      - d_oh-my-zsh-custom
      - f_bash_profile-for-zsh
      - f_zshenv
      - f_zshrc
  shared:
    dotfiles:
      - d_bin
      - d_config_gh
      - d_git_template
      - d_gradle_init_d
      - d_ssh
      - f_bash_sessions_disable
      - f_config_hub
      - f_curlrc
      - f_gitconfig
      - f_gitignore
      - f_gradle_properties
      - f_hgrc
      - f_hushlogin
      - f_tmux.conf
      - f_vimrc
      - f_wgetrc
      - fake_goenv
      - fake_pyenv
