config:
  backup: true
  create: true
  link_dotfile_default: link
  link_on_import: link
  dotpath: dotfiles
dotfiles:
  f_bashrc:
    src: bashrc
    dst: ~/.bashrc
  f_aliases:
    src: aliases
    dst: ~/.aliases
  f_bash_profile:
    src: bash_profile
    dst: ~/.bash_profile
  f_bash_prompt:
    src: bash_prompt
    dst: ~/.bash_prompt
  f_curlrc:
    src: curlrc
    dst: ~/.curlrc
  f_exports:
    src: exports
    dst: ~/.exports
  f_functions:
    src: functions
    dst: ~/.functions
  f_gitconfig:
    src: gitconfig
    dst: ~/.gitconfig
  f_hgrc:
    src: hgrc
    dst: ~/.hgrc
  f_path:
    src: path
    dst: ~/.path
  f_tmux.conf:
    src: tmux.conf
    dst: ~/.tmux.conf
  f_vimrc:
    src: vimrc
    dst: ~/.vimrc
  f_wgetrc:
    src: wgetrc
    dst: ~/.wgetrc
  d_gradle:
    src: gradle
    dst: ~/.gradle
    link: link_children
  d_ssh:
    src: ssh
    dst: ~/.ssh
    link: link_children
  d_desktop:
    src: Desktop
    dst: ~/Desktop
    link: link_children
  d_bin:
    src: bin
    dst: ~/bin
  d_fonts:
    src: Library/Fonts
    dst: ~/Library/Fonts
    link: link_children
  d_user:
    src: Library/Application Support/Sublime Text 3/Packages/User
    dst: ~/Library/Application Support/Sublime Text 3/Packages/User
    link: link_children
  f_hushlogin:
    src: hushlogin
    dst: ~/.hushlogin
profiles:
  acourtnrownsmbp.notcharlie.com:
    include:
    - default
  mini-me.notcharlie.com:
    include:
    - default
  default:
    dotfiles:
    - f_bashrc
    - f_aliases
    - f_bash_profile
    - f_bash_prompt
    - f_curlrc
    - f_exports
    - f_functions
    - f_gitconfig
    - f_hgrc
    - f_path
    - f_tmux.conf
    - f_vimrc
    - f_wgetrc
    - d_gradle
    - d_ssh
    - d_desktop
    - d_bin
    - d_fonts
    - d_user
    - f_hushlogin
