actions:
  _add_authorized_keys: |
    mkdir -p ~/.ssh
    op item get "Default key" --field "public key" > ~/.ssh/authorized_keys.default
    op item get "Confluent" --field "public key" > ~/.ssh/authorized_keys.confluent
    cat ~/.ssh/authorized_keys* | uniq > ~/.ssh/authorized_keys
  _install_package_control: "{{@@ _dotdrop_dotpath @@}}/../script/lib/install-package-control ~/\"{{@@ sublime_home @@}}\""
  _pyenv_install: |
    if [ -d ~/.pyenv ]; then
      git -C ~/.pyenv pull --prune origin;
    else
      git clone https://github.com/pyenv/pyenv.git ~/.pyenv;
    fi
  _goenv_install: |
    if [ -d ~/.goenv ]; then
      git -C ~/.goenv pull --prune origin;
    else
      git clone https://github.com/syndbg/goenv.git ~/.goenv;
    fi
  _nvm_install: |
    if [ -d ~/.nvm ]; then
      git -C ~/.nvm pull --prune origin;
    else
      git clone https://github.com/nvm-sh/nvm.git ~/.nvm;
    fi
  _cc_dotfiles_install: |
    if [ -d ~/.cc-dotfiles ]; then
      git -C ~/.cc-dotfiles pull --prune origin;
    else
      git clone https://github.com/confluentinc/cc-dotfiles.git ~/.cc-dotfiles;
    fi
config:
  backup: true
  create: true
  force_chmod: true
  link_dotfile_default: link
  link_on_import: link
  dotpath: dotfiles
  upignore:
    - .DS_Store
    - .localized
  cmpignore:
    - .DS_Store
    - .localized
dotfiles:
  d_bin:
    src: bin
    dst: ~/bin
  d_config_coursier:
    src: config/coursier
    dst: ~/.config/coursier
    chmod: 700
    link: link_children
  d_config_gh:
    src: config/gh
    dst: ~/.config/gh
    chmod: 700
    link: link_children
  d_config_glab_cli:
    src: config/glab-cli
    dst: ~/.config/glab-cli
    chmod: 700
    link: link_children
  d_config_pip:
    src: config/pip
    dst: ~/.config/pip
    link: link_children
  d_config_yapf:
    src: config/yapf
    dst: ~/.config/yapf
    link: link_children
  d_git_template:
    src: git-template
    dst: ~/.git-template
    link: nolink
  d_gradle_init_d:
    src: gradle/init.d
    dst: ~/.gradle/init.d
    link: link_children
  d_oh-my-zsh-custom:
    src: oh-my-zsh-custom
    dst: ~/.oh-my-zsh-custom
    link: link_children
    chmod: 700
  d_user:
    src: Library/Application Support/Sublime Text 3/Packages/User
    dst: "~/{{@@ sublime_home @@}}/Packages/User"
    link: link_children
    actions:
      - _install_package_control
    upignore:
      - oscrypto-ca-bundle.crt
      - Package Control.cache
      - Package Control.last-run
      - Package Control.merged-ca-bundle
      - Package Control.user-ca-bundle
    cmpignore:
      - oscrypto-ca-bundle.crt
      - Package Control.cache
      - Package Control.last-run
      - Package Control.merged-ca-bundle
      - Package Control.user-ca-bundle
  f_bash_sessions_disable:
    src: bash_sessions_disable
    dst: ~/.bash_sessions_disable
  f_bash_profile-for-zsh:
    src: bash_profile-for-zsh
    dst: ~/.bash_profile
  f_bazelrc:
    src: bazelrc
    dst: ~/.bazelrc
    chmod: 600
  f_curlrc:
    src: curlrc
    dst: ~/.curlrc
  f_finicky.js:
    src: finicky.js
    dst: ~/.finicky.js
  f_gitconfig:
    src: gitconfig
    dst: ~/.gitconfig
  f_gitconfig-confluent:
    src: gitconfig-confluent
    dst: ~/.gitconfig-confluent
  f_gitignore:
    src: gitignore
    dst: ~/.gitignore
  f_gradle_properties:
    src: gradle/gradle.properties
    dst: ~/.gradle/gradle.properties
    chmod: 600
  f_hgrc:
    src: hgrc
    dst: ~/.hgrc
  f_hushlogin:
    src: hushlogin
    dst: ~/.hushlogin
  f_m2_settings_confluent:
    src: m2/settings_confluent.xml
    dst: ~/.m2/settings.xml
    chmod: 600
    link: nolink
  f_m2_settings_home:
    src: m2/settings_home.xml
    dst: ~/.m2/settings.xml
    chmod: 600
    link: nolink
  f_netrc:
    src: netrc
    dst: ~/.netrc
    chmod: 600
  f_pypirc_home:
    src: pypirc_home
    dst: ~/.pypirc
    chmod: 600
  f_ssh_authorized_keys:
    src:
    dst:
    actions:
      - _add_authorized_keys
  f_ssh_config:
    src: ssh/config
    dst: ~/.ssh/config
  f_ssh_known_hosts:
    src: ssh/known_hosts
    dst: ~/.ssh/known_hosts
  f_sublime_license:
    src: Library/Application Support/Sublime Text 3/Local/License.sublime_license
    dst: "~/{{@@ sublime_home @@}}/Local/License.sublime_license"
    chmod: 600
    link: nolink
  f_tmux.conf:
    src: tmux.conf
    dst: ~/.tmux.conf
  f_vimrc:
    src: vimrc
    dst: ~/.vimrc
  f_wgetrc:
    src: wgetrc
    dst: ~/.wgetrc
  f_zshenv:
    src: zshenv
    dst: ~/.zshenv
  f_zshrc:
    src: zshrc
    dst: ~/.zshrc
  fake_cc_dotfiles:
    src:
    dst:
    actions:
      - _cc_dotfiles_install
  fake_pyenv:
    src:
    dst:
    actions:
      - _pyenv_install
  fake_goenv:
    src:
    dst:
    actions:
      - _goenv_install
  fake_nvm:
    src:
    dst:
    actions:
      - _nvm_install
profiles:
  abrown-confluent:
    dotfiles:
    include:
      - default
      - mac
      - confluent
  abrown-confluent.local:
    dotfiles:
    include:
      - abrown-confluent
  abrown-confluent.notcharlie.com:
    dotfiles:
    include:
      - abrown-confluent
  adams-mbp:
    include:
      - default
      - mac
      - personal
  adams-mbp.local:
    dotfiles:
    include:
      - adams-mbp
  adams-mbp.notcharlie.com:
    dotfiles:
    include:
      - adams-mbp
  exhubber:
    dotfiles:
    include:
      - default
      - mac
      - personal
  exhubber.local:
    dotfiles:
    include:
      - exhubber
  exhubber.notcharlie.com:
    dotfiles:
    include:
      - exhubber
  mac:
    variables:
      sublime_home: Library/Application Support/Sublime Text 3
      mac: true
      ssh_agent: "{{@@ env['HOME'] @@}}/Library/Group Containers/2BUA8C4S2C.com.1password/t/agent.sock"
    dotfiles:
      - d_user
      - f_finicky.js
      - f_sublime_license
  linux_desktop:
    variables:
      sublime_home: .config/sublime-text-3
      ssh_agent: "{{@@ env['HOME'] @@}}/.1password/agent.sock"
    dotfiles:
      - d_user
      - f_sublime_license
  linux:
    dotfiles:
    variables:
      linux: true
  personal:
    dotfiles:
      - d_config_pip
      - f_m2_settings_home
      - f_pypirc_home
    variables:
      personal: true
  confluent:
    variables:
      confluent: true
    dotfiles:
      - d_config_coursier
      - d_config_yapf
      - f_gitconfig-confluent
      - f_m2_settings_confluent
      - f_netrc
      - fake_cc_dotfiles
      - fake_nvm
  default:
    dotfiles:
    variables:
      confluent: false
      linux: false
      mac: false
      personal: false
      ssh_agent: ''
    dynvariables:
      buildbuddy_dev_ro_key: op item get BuildBuddy --field "cflt-devprod-test Dev-RO key"
      buildbuddy_readwrite_key: op item get BuildBuddy --field "Read+Write API key"
      firefox_me_ids: op item list --tags Firefox:Me --format=json | jq '.[].id'
      full_name: op item get 2rou2jbvdvahrl4ov7wtxstdka --fields "first name,last name" | tr ',' ' '
      gh_cli_token: op item get "GitHub" --fields "gh cli token"
      gitea_maven_token: op item get "Gitea (acourtneybrown)" --field "Maven token"
      gitea_pypi_token: op item get "Gitea (acourtneybrown)" --field "PyPI token"
      gitea_username: op item get "Gitea (acourtneybrown)" --field username
      gitea_website: op item get "Gitea (acourtneybrown)" --format json | jq -r '.urls[0].href'
      github_account: op item get "GitHub" --fields username
      github_netrc_token: op item get "GitHub" --fields "Confluent netrc"
      gitlab_account: op item get "GitLab" --field username
      glab_cli_token: op item get "GitLab" --field "glab cli token"
      homebrew_prefix: brew --prefix
      okta_username: op item get "Okta" --field username
      personal_email: op item get 2rou2jbvdvahrl4ov7wtxstdka --field email
      personal_public_key: op item get "Default key" --field "public key"
      sublime_text_license: op item get "Sublime Text 4+" --field "license key"
      work_email: echo "$({{@@ okta_username @@}})@confluent.io"
      work_public_key: op item get Confluent --field "public key"
    include:
      - zsh
  zsh:
    include:
      - shared
    dotfiles:
      - d_oh-my-zsh-custom
      - f_bash_profile-for-zsh
      - f_zshenv
      - f_zshrc
  shared:
    dotfiles:
      - d_bin
      - d_config_gh
      - d_config_glab_cli
      - d_git_template
      - d_gradle_init_d
      - f_bash_sessions_disable
      - f_bazelrc
      - f_curlrc
      - f_gitconfig
      - f_gitignore
      - f_gradle_properties
      - f_hgrc
      - f_hushlogin
      - f_ssh_authorized_keys
      - f_ssh_config
      - f_ssh_known_hosts
      - f_tmux.conf
      - f_vimrc
      - f_wgetrc
      - fake_goenv
      - fake_pyenv
