actions:
  add_authorized_keys: cat ~/.ssh/authorized_keys* | uniq > ~/.ssh/authorized_keys
config:
  backup: true
  create: true
  link_dotfile_default: link
  link_on_import: link
  dotpath: dotfiles
  upignore:
  - .DS_Store
  - .localized
  cmpignore:
  - .DS_Store
  - .localized
dotfiles:
  f_bashrc:
    src: bashrc
    dst: ~/.bashrc
  f_aliases:
    src: aliases
    dst: ~/.aliases
  f_bash_profile:
    src: bash_profile
    dst: ~/.bash_profile
  f_bash_prompt:
    src: bash_prompt
    dst: ~/.bash_prompt
  f_curlrc:
    src: curlrc
    dst: ~/.curlrc
  f_exports:
    src: exports
    dst: ~/.exports
  f_functions:
    src: functions
    dst: ~/.functions
  f_gitconfig:
    src: gitconfig
    dst: ~/.gitconfig
  f_hgrc:
    src: hgrc
    dst: ~/.hgrc
  f_path:
    src: path
    dst: ~/.path
  f_tmux.conf:
    src: tmux.conf
    dst: ~/.tmux.conf
  f_vimrc:
    src: vimrc
    dst: ~/.vimrc
  f_wgetrc:
    src: wgetrc
    dst: ~/.wgetrc
  d_gradle:
    src: gradle
    dst: ~/.gradle
    link: link_children
    upignore:
    - caches
    - daemon
    - native
    - notifications
    - workers
    - wrapper
    cmpignore:
    - caches
    - daemon
    - native
    - notifications
    - workers
    - wrapper
  d_ssh:
    src: ssh
    dst: ~/.ssh
    link: link_children
    upignore:
    - id_rsa*
    - sockets
    - synology*
    - authorized_keys
    cmpignore:
    - id_rsa*
    - sockets
    - synology*
    - authorized_keys
    actions:
    - add_authorized_keys
  d_desktop:
    src: Desktop
    dst: ~/Desktop
    link: link_children
  d_bin:
    src: bin
    dst: ~/bin
  d_fonts:
    src: Library/Fonts
    dst: ~/Library/Fonts
    link: link_children
  d_user:
    src: Library/Application Support/Sublime Text 3/Packages/User
    dst: ~/Library/Application Support/Sublime Text 3/Packages/User
    link: link_children
    upignore:
    - Package Control*
    - oscrypto-ca-bundle.crt
    cmpignore:
    - Package Control*
    - oscrypto-ca-bundle.crt
  f_hushlogin:
    src: hushlogin
    dst: ~/.hushlogin
  f_gitconfig-github:
    src: gitconfig-github
    dst: ~/.gitconfig-github
  f_gitignore:
    src: gitignore
    dst: ~/.gitignore
  f_zshrc:
    src: zshrc
    dst: ~/.zshrc
  d_oh-my-zsh-custom:
    src: oh-my-zsh-custom
    dst: ~/.oh-my-zsh-custom
    link: link_children
  f_zshenv:
    src: zshenv
    dst: ~/.zshenv
  f_finicky.js:
    src: finicky.js
    dst: ~/.finicky.js
profiles:
  default:
    include:
    - zsh
  acourtnrownsmbp:
    include:
    - acourtnrownsmbp.notcharlie.com
  acourtneybrowns-MacBook-Pro.local:
    include:
    - acourtnrownsmbp.notcharlie.com
  acourtnrownsmbp.notcharlie.com:
    include:
    - default
    - mac
  mini-me.notcharlie.com:
    include:
    - default
    - mac
  mac:
    dotfiles:
    - f_finicky.js
    - d_desktop
    - d_fonts
    - d_user
  shared:
    dotfiles:
    - f_curlrc
    - f_gitconfig
    - f_gitconfig-github
    - f_gitignore
    - f_hgrc
    - f_hushlogin
    - f_tmux.conf
    - f_vimrc
    - f_wgetrc
    - d_gradle
    - d_ssh
    - d_bin
  zsh:
    include:
    - shared
    dotfiles:
    - f_zshrc
    - d_oh-my-zsh-custom
    - f_zshenv
  bash:
    include:
    - shared
    dotfiles:
    - f_bashrc
    - f_aliases
    - f_bash_profile
    - f_bash_prompt
    - f_exports
    - f_functions
    - f_path
