#!/usr/bin/env zsh
# shellcheck disable=SC1071

LOCAL_CMD="$(basename "${(%):-%N}")"
if [[ -n $OP_PLUGIN_ALIASES_SOURCED ]]; then
  exec op plugin run -- "$LOCAL_CMD" "$@"
else
  exec "$LOCAL_CMD" "$@"
fi
