github.com:
    oauth_token: {{@@ gh_cli_token @@}}
    user: {{@@ github_account @@}}
    git_protocol: ssh
    users:
        {{@@ github_account @@}}:
            oauth_token: {{@@ gh_cli_token @@}}
