#!/usr/bin/env bash

function fake_ldd() {
  local GLIBC_VERSION

  if [[ $(/usr/lib/libc.so.6 | /bin/grep "GNU C Library") =~ version\ ([^ ]+)\.\$ ]]; then
    GLIBC_VERSION="${BASH_REMATCH[1]}"
  fi
  echo "ldd ${GLIBC_VERSION:-2.20}"
}

fake_ldd
