logins:
- name: {{@@ gitea_hostname @@}}
  url: {{@@ gitea_website @@}}
  token: {{@@ tea_cli_token @@}}
  default: false
  ssh_host: {{@@ gitea_hostname @@}}
  ssh_key: ""
  insecure: false
  user: {{@@ gitea_username @@}}
  created: 1716146169
preferences:
  editor: false
  flag_defaults:
    remote: ""
