#!/usr/bin/env bash

set -e
cd "$(dirname "${0}")/.."

# shellcheck disable=SC1091
. script/functions

extract_gpg_key acourtneybrown@gmail.com
ensure_brewfile_installed Brewfile.personal

enable_pyenv
enable_goenv

pipx_install 3.11 python-kasa python-vipaccess

mkdir -p "${HOME}/personal"
(
  cd "${HOME}/personal"

  pyenv local "$(ensure_pyenv_version 3.11)"
  goenv local "$(ensure_goenv_version 1.19)"
)
