#!/usr/bin/env bash

set -e
cd "$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")"

# shellcheck disable=SC1091
. lib/util.sh
# shellcheck disable=SC1091
. lib/profile.sh

function ensure_profile_includes() {
  local profile
  local include

  profile=${1}
  include=${2}

  present=$(yq e "[\"${include}\"] - (.profiles.\"${profile}\".include // []) | length == 0" ../config.yaml)
  if [[ ${present} == "false" ]]; then
    yq eval ".profiles.\"${profile}\".\"include\" += [\"${include}\"]" -i ../config.yaml
  fi
}

function list_includes() {
  local profile
  profile="${1}"
  yq eval ".profiles.\"${profile}\".include[]" ../config.yaml
}

function set_host_ssh_key_name_if_present() {
  local profile
  local key_name

  profile=${1}
  key_name="${profile} key"

  if op item get "${key_name}" >/dev/null 2>&1; then
    yq eval ".profiles.\"${profile}\".variables.host_ssh_key_name = \"${key_name}\"" -i ../config.yaml
  fi
}

function main() {
  if ! command -v brew >/dev/null; then
    echo "need sudo permission for initial Homebrew install"
    util::is_mac && util::sudo_check_then_alive
    profile::install_homebrew
  fi

  if ! command -v yq >/dev/null; then
    brew install yq
  fi

  for action in _goenv_install _pyenv_install; do
    profile::run_dotdrop_action "${action}"
  done

  # create a new profile (if necessary), including default & os-specific ones
  PROFILE=$(hostname)
  explicit_profiles=()
  if util::is_mac; then
    explicit_profiles+=(mac)
  elif util::is_linux; then
    explicit_profiles+=(linux)
  elif util::is_synology_dsm; then
    explicit_profiles+=(synology_dsm)
  else
    explicit_profiles+=(default)
  fi
  explicit_profiles+=("${@}")
  for named in "${explicit_profiles[@]}"; do
    ensure_profile_includes "${PROFILE}" "${named}"
  done

  declare -A seen=()
  declare -a uniq_profiles=()
  profile_includes=($(list_includes "${PROFILE}"))
  while (( ${#profile_includes[@]} )); do
    current="${profile_includes[0]}"
    profile_includes=( "${profile_includes[@]:1}" )
    declare -a work_queue=($current)
    declare -a item_stack=()
    while (( ${#work_queue[@]} )); do
      item="${work_queue[0]}"
      work_queue=( "${work_queue[@]:1}" )
      if [[ -z ${seen[$item]+x} ]]; then   # key not yet seen
        item_stack=( "$item" "${item_stack[@]}" )
        seen[$item]=1
        included_profiles=($(list_includes "${item}"))
        if (( ${#included_profiles[@]} )); then
          work_queue=( "${included_profiles[@]}" "${work_queue[@]}")
        fi
      fi
    done

    uniq_profiles+=("${item_stack[@]}")
  done
  echo "profiles to apply ( ${uniq_profiles[@]} )"

  for named in "${uniq_profiles[@]}"; do
    echo "start of profile <$named>"
    profile::ensure_brewfile_installed "./lib/resources/Brewfile.${named}"
    if command -v "profile::${named}"; then
      "profile::${named}"
    fi
  done

  eval "$(op signin)"
  set_host_ssh_key_name_if_present "${PROFILE}"

  # Install all dotfiles into the home directory
  dotdrop install --force --profile="${PROFILE}" --cfg ../config.yaml

  for named in "${uniq_profiles[@]}"; do
    if command -v "profile::${named}_after"; then
      "profile::${named}_after"
    fi
  done

  profile::finalize
}

main "${@}"
