#!/usr/bin/env bash
set -e
cd "$(dirname "${0}")/.."

# shellcheck disable=SC1091
. script/functions

ensure_brewfile_installed Brewfile.confluent

enable_pyenv
pipx_install 3.8 confluent-release-tools
pipx_install 3.9 confluent-ci-tools
pipx_install 3.11 ansible-hostmanager bump2version gimme-aws-creds gql tox

pyenv install --skip-existing "$(pyenv latest --known 3.11)"
pyenv global "$(pyenv latest --known 3.11)"

goenv install --skip-existing "$(goenv install -l | grep 1.19 | tail -1)"
goenv global "$(goenv install -l | grep 1.19 | tail -1)"

# jenv
