#!/usr/bin/env bash

set -e
cd "$(dirname "${0}")/.."

# shellcheck disable=SC1091
. script/functions

ensure_brewfile_installed Brewfile.home

enable_pyenv
pipx_install 3.11 python-kasa python-vipaccess
