#!/usr/bin/env bash
set -e
cd "$(dirname "${0}")/.."

# shellcheck disable=SC1091
. script/functions

ensure_brewfile_installed Brewfile.confluent

enable_pyenv
enable_goenv
enable_jenv

pipx_install 3.8 confluent-release-tools
pipx_install 3.9 confluent-ci-tools
pipx_install 3.11 ansible-hostmanager bump2version gimme-aws-creds gql tox

pyenv global "$(ensure_pyenv_version 3.11)"
goenv global "$(ensure_goenv_version 1.19)"

jenv add /Library/Java/JavaVirtualMachines/temurin-11.jdk/Contents/Home
jenv global 11
