#!/usr/bin/env bash

set -e

cd "$(dirname "$0")/.."
. script/functions
# sudo_check_then_alive

# Set up dotdrop dependencies
git submodule update --init --recursive
git submodule update --remote dotdrop

script/setup-dotdrop-venv.sh

# Install oh-my-zsh
if [ ! -d ~/.oh-my-zsh ]; then
  if command -v curl; then
    sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh) --unattended"
  elif command -v wget; then
    sh -c "$(wget https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh -O -) --unattended"
  else
    abort "Either curl or wget must be installed"
  fi
fi

# Install all dotfiles into the home directory
if [ ! $(command -v yq) ]; then
  go install github.com/mikefarah/yq/v3@latest
fi

# create a new profile (if necessary) and include default
PROFILE=$(hostname)
if [ -z "$(yq r config.yaml profiles.\"$PROFILE\")" ]; then
  yq w -i config.yaml profiles.\"$PROFILE\"."include[+]" default
  if is_mac; then
    yq w -i config.yaml profiles.\"$PROFILE\"."include[+]" mac
  fi
fi
./dotdrop.sh install --force --profile=$PROFILE
