#!/usr/bin/env bash

set -e
cd "$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")"

# shellcheck disable=SC1091
. lib/util.sh
# shellcheck disable=SC1091
. lib/profile.sh

function ensure_profile_includes() {
  local profile
  local include

  profile=${1}
  include=${2}

  present=$(yq e "[\"${include}\"] - .profiles.\"${profile}\".include | length == 0" ../config.yaml)
  if [[ ${present} == "false" ]]; then
    yq eval ".profiles.\"${profile}\".\"include\" += [\"${include}\"]" -i ../config.yaml
  fi
}

function list_includes() {
  local profile
  profile="${1}"
  yq eval ".profiles.\"${profile}\".include[]" ../config.yaml
}

function main() {
  if ! command -v brew >/dev/null; then
    echo "need sudo permission for initial Homebrew install"
    util::is_mac && util::sudo_check_then_alive
    profile::install_homebrew
  fi

  if ! command -v yq >/dev/null; then
    brew install yq
  fi

  for action in _goenv_install _pyenv_install; do
    profile::run_dotdrop_action "${action}"
  done

  # create a new profile (if necessary), including default & os-specific ones
  PROFILE=$(hostname)
  included_profiles=(default)
  if util::is_mac; then
    included_profiles+=(mac)
  fi
  if util::is_linux; then
    included_profiles+=(linux)
  fi
  included_profiles+=("${@}")
  for named in "${included_profiles[@]}"; do
    ensure_profile_includes "${PROFILE}" "${named}"
  done

  for named in $(list_includes "${PROFILE}"); do
    if command -v "profile::${named}"; then
      "profile::${named}"
    fi
  done

  eval "$(op signin)"

  # Install all dotfiles into the home directory
  dotdrop install --force --profile="${PROFILE}" --cfg ../config.yaml

  for named in $(list_includes "${PROFILE}"); do
    ensure_profile_includes "${PROFILE}" "${named}"
    if command -v "profile::${named}_after"; then
      "profile::${named}_after"
    fi
  done
}

main "${@}"
