#!/usr/bin/env bash

BASEDIR="$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")"
TMPFILE="$(mktemp "${TMPDIR:-/tmp}/1password-settings.json.XXXXXX")"
trap 'rm -f $TMPFILE' INT QUIT TERM ILL PIPE

"$BASEDIR"/update-1password-settings "$TMPFILE"
jd "$BASEDIR"/lib/resources/1password-settings.json "$TMPFILE"
