#!/usr/bin/env bash

BASEDIR="$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")"
TMPFILE="$(mktemp "${TMPDIR:-/tmp}/1password-settings.jso.XXXXXX")"
"$BASEDIR"/update-1password-settings "$TMPFILE"
jd "$BASEDIR"/lib/resources/1password-settings.json "$TMPFILE"
