#!/usr/bin/env bash

set -e
cd "$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")"

# shellcheck disable=SC1091
. lib/functions
sudo_check_then_alive

[ -z "${SKIP_UPDATES}" ] && install_updates

if is_mac; then
  echo "Enable Full Disk access for Terminal.  System Preferences > Security & Privacy > Privacy"
  echo "Do this first, before running the script again."
  read -r _

  open -a 'App Store.app'
  echo "Login to Apple ID.  Press <enter> when done."
  read -r _

  # install xcode command line tools
  lib/install-xcode.sh

  # MacOS customization script
  ./macos

  # ensure that NFS options are set
  update_nfs
elif is_linux; then
  # On Raspberry Pi, ensure en_US.UTF-8 locale available & installed
  if [ -f /etc/locale.gen ]; then
    sudo sed -i 's/# en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/g' /etc/locale.gen
    sudo locale-gen en_US.UTF-8
    sudo update-locale en_US.UTF-8
  fi
fi
