#!/usr/bin/env bash

set -e

cd "$(dirname "${0}")/.."
. script/functions
sudo_check_then_alive

# Check and install any remaining software updates.
if is_mac; then
  install_updates

  # install xcode command line tools
  script/install-xcode.sh

  # MacOS customization script
  script/macos

  # install homebrew
  script/install-homebrew.sh
  open -a 'App Store.app'
  echo "Login to Apple ID.  Press <enter> when done."
  read -r _

  # install LaunchDaemon to ensure mosh is added to fw allow list
  script/install-fix-mosh.sh
  ensure_ssh_enabled
  ensure_screen_share_enabled
elif is_linux; then
  script/install-linuxbrew.sh
fi

[ -z "${SKIP_BUNDLE}" ] && ensure_brewfile_installed
[ -z "${SKIP_HOME}" ] && ensure_brewfile_installed Brewfile.home

script/extract-onepassword-secrets.sh

# Setup development tools
script/golang-setup.sh
script/goenv-setup.sh
script/python-setup.sh
[ -z "${SKIP_CONFLUENT}" ] && script/confluent-setup.sh
