#!/usr/bin/env bash

DEF_FILE="$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")/lib/resources/1password-settings.json"
OUTFILE="${1:-$DEF_FILE}"

jq 'with_entries(select(.key | IN("authTags") | not))' \
  ~/Library/Group\ Containers/2BUA8C4S2C.com.1password/Library/Application\ Support/1Password/Data/settings/settings.json \
  > "$OUTFILE"
