#!/usr/bin/env bash

set -e

cd "$(dirname "$0")/.."
. script/functions
sudo_check_then_alive

if is_mac; then
  install_updates
fi

[ -z "$SKIP_BUNDLE" ] && script/brew_bundle

./dotdrop.sh install

script/golang-setup.sh
script/ruby-setup.sh
