#!/usr/bin/env bash

# shellcheck disable=SC1091
. "$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")/lib/util.sh"

DEF_FILE="$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")/lib/resources/1password-settings.json"
OUTFILE="${1:-$DEF_FILE}"

if util::is_mac; then
  SETTINGS_FILE=~/"Library/Group Containers/2BUA8C4S2C.com.1password/Library/Application Support/1Password/Data/settings/settings.json"
elif util::is_linux; then
  SETTINGS_FILE=~/.config/1Password/settings/settings.json
else
  abort "uncertain location for 1Password settings.json file"
fi

jq 'with_entries(select(.key | IN("authTags") | not))' "$SETTINGS_FILE" > "$OUTFILE"
