#!/usr/bin/env bash

set -e

cd "$(dirname "$0")/.."
. script/functions
sudo_keepalive

install_updates
script/brew_bundle
populate_dotenv

# TODO: update dotdrop?

script/golang-setup.sh
script/ruby-setup.sh
