#!/bin/sh

cd "$(dirname $0)/.."

script/bootstrap

populate_dotenv

# Install all dotfiles into the home directory
git submodule update --init --recursive
git submodule update --remote dotdrop
virtualenv -p python3 env
source env/bin/activate
pip install -r dotdrop/requirements.txt
deactivate
./dotdrop.sh install --profile=default
