#!/bin/sh
# Install all dotfiles into the home directory

cd "$(dirname $0)/.."
git submodule update --init --recursive
git submodule update --remote dotdrop
virtualenv -p python3 env
source env/bin/activate
pip install -r dotdrop/requirements.txt
./dotdrop.sh install

# Setup to ensure fewer Duo pushes
mkdir -p ~/.ssh/sockets
chmod 0700 ~/.ssh/sockets

# TODO: pull ssh private key from 1Password
# TODO: pull GPG key from 1Password